add observation wrapper
rarick/football pull request #20
Opened 2021-04-23 14:16 UTC by AdrianaVega97

Added Observation Embedding:
Extended their Simple115V by adding :
relative pose(position) among teammates and opponents
relative pose between active player and ball
sticky actions/card/tried factor status

2021-04-24 20:50 UTC, rarick requested changes

2021-04-24 20:50 UTC, rarick commented on partyball/env/party_wrapper.py
> +import cv2
Not used

2021-04-24 20:50 UTC, rarick commented on partyball/env/party_wrapper.py
> +import collections
Not used

2021-04-24 20:50 UTC, rarick commented on partyball/env/party_wrapper.py
> +from __future__ import absolute_import
Not used

2021-04-24 20:50 UTC, rarick commented on partyball/env/party_wrapper.py
> +from __future__ import division
Not used

2021-04-24 20:50 UTC, rarick commented on partyball/env/party_wrapper.py
> +from __future__ import print_function
Not used

2021-04-24 20:50 UTC, rarick commented on partyball/env/party_wrapper.py
> +from gfootball.env import football_action_set
Not used

2021-04-24 20:50 UTC, rarick commented on partyball/env/party_wrapper.py
> +from gfootball.env import observation_preprocessing
Not used

2021-04-24 20:50 UTC, rarick commented on partyball/env/party_wrapper.py
> +    def do_flatten(obj):
This should be a private static method rather than a local definition

2021-04-24 20:50 UTC, rarick commented on partyball/env/party_wrapper.py
> +
Cut down this white space to a single line

2021-04-24 20:50 UTC, rarick commented on partyball/env/party_wrapper.py
> +
Cut down this white space to a single line

2021-04-24 20:50 UTC, rarick commented on partyball/env/party_wrapper.py
> +          rel_pos_teamates.append(rel_pos)
In the `if` and `elif` cases, `rel_pos` results in a list type.
In the `else` case, `rel_pos` is of type `np.ndarray`. This seems like it could be an issue

2021-04-24 20:50 UTC, rarick commented on partyball/env/party_wrapper.py
> +          rel_pos_opponents.append(rel_pos)
Same list/array concerns as before. Also this is very similar code to the above, just the team key got changed.

2021-04-24 20:50 UTC, rarick commented on partyball/env/party_wrapper.py
> +      o.extend(do_flatten(rel_pos_opponents))
There are relative positions for `left_team -> left_team` and `left_team -> right_team`, but none for `right_team -> right_team`. That will be an issue

2021-04-25 13:27 UTC, rarick requested changes

2021-04-25 13:27 UTC, rarick commented on partyball/env/party_wrapper.py
> +      rel_pos_teamates_left = PartyObservationWrapper.create_rel_pose(obs['right_team'], obs['left_team_active'], obs['left_team'], obs['left_team_active'])
Keep maximum line length to 79 characters:
https://www.python.org/dev/peps/pep-0008/#id19

2021-04-25 13:27 UTC, rarick commented on partyball/env/party_wrapper.py
> +      rel_pos_teamates_right = PartyObservationWrapper.create_rel_pose(obs['right_team'], obs['right_team_active'], obs['right_team'], obs['right_team_active'])
Keep maximum line length to 79 characters:
https://www.python.org/dev/peps/pep-0008/#id19

2021-04-25 13:27 UTC, rarick commented on partyball/env/party_wrapper.py
> +      rel_pos_teamates_left = PartyObservationWrapper.create_rel_pose(obs['right_team'], obs['left_team_active'], obs['left_team'], obs['left_team_active'])
This seems incorrect. I think it should be the following:
```
      rel_pos_left_left = PartyObservationWrapper.create_rel_pose(
        obs[left_team'], obs['left_team_active'], obs['left_team'], obs['left_team_active'])
      rel_pos_left_right = PartyObservationWrapper.create_rel_pose(
        obs[left_team'], obs['left_team_active'], obs['right_team'], obs['right_team_active'])
      rel_pos_right_right = PartyObservationWrapper.create_rel_pose(
        obs[right_team'], obs['right_team_active'], obs['right_team'], obs['right_team_active'])
```

2021-04-25 13:27 UTC, rarick commented on partyball/env/party_wrapper.py
> +      rel_pos_teamates_left = PartyObservationWrapper.create_rel_pose(obs['right_team'], obs['left_team_active'], obs['left_team'], obs['left_team_active'])
This compares left -> left, left -> right, and right -> right

2021-04-25 13:27 UTC, rarick commented on partyball/env/party_wrapper.py
> +      rel_pos_opponents_right = PartyObservationWrapper.create_rel_pose(obs['right_team'], obs['right_team_active'], obs['left_team'], obs['left_team_active'])
I don't think it's necessary to have both left -> right and right -> left. The networks will not have any difficult in inverting a sign to get the other. 

No advantage is given by having one and not the other. Only `left -> right` or `right -> left` is necessary.

2021-04-25 13:27 UTC, rarick commented on partyball/env/party_wrapper.py
> +
Don't have 2 white space lines unless you're starting a new class or function definition outside the class

https://www.python.org/dev/peps/pep-0008/#id21

2021-04-25 13:27 UTC, rarick commented on partyball/env/party_wrapper.py
> +
https://www.python.org/dev/peps/pep-0008/#id21

2021-04-25 13:27 UTC, rarick commented on partyball/env/party_wrapper.py
> +
blank lines bad

2021-04-25 13:47 UTC, AdrianaVega97 commented on partyball/env/party_wrapper.py
> +      rel_pos_teamates_left = PartyObservationWrapper.create_rel_pose(obs['right_team'], obs['left_team_active'], obs['left_team'], obs['left_team_active'])
I know but I thought that's what you meant when you said that we only had the relative position from one team in your last comment.

2021-04-25 19:14 UTC, rarick commented
Looks good to me!

2021-04-25 19:14 UTC, rarick approved these changes
:+1:

2021-04-25 19:15 UTC, merged